import { Association } from '../models/association';
export function getAssociations() {
  const associations: { [id: string]: Association[] } = {
    'One-Stop Shop': [
      {
        id: '036b9d9a-c063-40a7-a029-a555e9ae3b72',
        brand: 'One-Stop Shop',
        publish: '',
        trend: 'Solar powered gadgets',
        term: 'Suncatcher portable solar charger',
        relationship: true,
        reason: `A 'Suncatcher portable solar charger' is a specific type of solar powered gadget. It's designed to charge other devices using solar energy, making it a direct example of a solar powered gadget.`,
        sku: 'ABCD23455',
        keywords: ['charger', 'portable charger', 'solar portable charger'],
        testUrl: '',
        headlines: [
          'Solar Power On-the-Go',
          'Solar Charger: Power Up',
          'Solar Power Source',
          'Solar Gadgets: Suncatcher',
          'Power Up with Suncatcher',
          'Solar Power On The Go	',
          'Go Solar with Suncatcher',
          'Solar Power Solutions	',
          'Solar Power: Suncatcher',
          'Suncatcher: Sustainable Power	',
          'Solar power on the go	',
          'Suncatcher: Charge with sun	',
          'Power up with Suncatcher	',
          'SuperStore: Solar chargers	',
          'Solar Power On The Go!',
        ],
        descriptions: [
          'Power up with Suncatcher! Solar charger for adventures.',
          'Suncatcher: Solar powered gadgets, on the go.',
          'Stay charged with Suncatcher. Solar power, anytime.',
          'SuperStore: Suncatcher solar charger, harness the sun.',
        ],
        campaignId: '2133454',
        adGroupId: '556787',
      },
    ] as Association[],
    'Fitness Glow': [
      {
        id: '50151468-3bb7-49a4-adca-8ff5eb28121f',
        brand: 'Fitness Glow',
        publish: '',
        trend: 'Hiking boots for women',
        term: 'Trekqueen waterproof hiking boots',
        relationship: true,
        reason: `Trekqueen waterproof hiking boots are a specific type of hiking boots.  While the description doesn't explicitly state they are for women, the term 'Hiking boots for women' is a broader category that Trekqueen waterproof hiking boots could fall under.`,
        sku: 'AHDF456965',
        keywords: ['hiking', 'outdoors', 'hiking boots'],
        testUrl: '',
        headlines: [
          'Hiking Boots for Women',
          'Trekqueen Hiking Boots',
          'Trekqueen: Comfort & Support	',
          'Explore with Trekqueen Boots',
          'Durable Women"s Hiking Boots',
          'Trekqueen: Any Weather',
          'Hiking	Shop Women"s Hiking Boots Now	',
          'SuperStore: Trekqueen Sale',
          'Hiking Boots: Trekqueen',
          'Trekqueen: Conquer Any Trail	',
          'SuperStore: Trekqueen Boots	',
          'Shop Trekqueen Hiking Boots	',
          'Waterproof Hiking Boots	',
          'Women`s Hiking Boots	',
          'Trekqueen Boots at SuperStore',
        ],
        descriptions: [
          'Trekqueen Waterproof Hiking Boots: Conquer any trail.',
          'Shop SuperStore!	Women"s Hiking Boots? Trekqueen"s waterproof & durable. Shop now!	',
          'Explore confidently with Trekqueen Waterproof Hiking Boots. For women.	',
          'Waterproof Hiking Boots for Women? Trekqueen. Shop SuperStore.',
        ],
        campaignId: '2133454',
        adGroupId: '556787',
      },
    ] as Association[],
    'Skin Experts': [
      {
        id: '50151468-3bb7-49a4-adca-8ff5eb28121f',
        brand: 'Skin Experts',
        publish: '',
        trend: 'Skincare',
        term: 'Purify & protect facial cleanser',
        relationship: true,
        reason: `Facial cleansers are a fundamental part of a skincare routine. The description of 'Purify & protect facial cleanser' explicitly mentions removing impurities and makeup, which are key steps in skincare.  Additionally, the product's claim of being suitable for all skin types further reinforces its connection to skincare as it addresses a broad range of skin concerns.`,
        sku: 'KSDFJE23455',
        keywords: ['hiking', 'outdoors', 'hiking boots'],
        testUrl: '',
        headlines: [
          'Purify & protect, shop now!',
          'Gentle cleanse, all skin types',
          ,
          'Remove impurities, makeup free',
          'Balanced skin, SuperStore',
          'Refresh & protect your skin',
          'Protect your skin',
          'Cleanse & protect, SuperStore',
          'Healthy skin starts here',
          'All skin types, SuperStore',
          'Skin Secret: Purify & Protect',
          'Shop now, SuperStore',
          'Skincare routine, SuperStore',
          'Gentle cleanse, balanced skin',
          'Purify & protect, now!',
          'Purify & protect skin',
        ],
        descriptions: [
          'Purify & protect: Gentle cleanser for all skin types. Shop now at SuperStore.',
          'Purify & protect: Gentle cleanser for all skin types. Shop now at SuperStore.',
          'Refresh & balance your skin. Purify & protect facial cleanser. SuperStore.',
          'All skin types welcome! Purify & protect facial cleanser. Shop SuperStore.',
        ],
        campaignId: '5674534',
        adGroupId: '6785456',
      },
    ] as Association[],
  };

  return associations;
}
